name: Angular CI

run-name: ${{ github.actor }} is learning GitHub Actions

on:
  push:
    branches: [ master ]

jobs:
  install-and-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: npm install and npm run CI commands
        run: |
          npm i
          npm run build
